### ISSUE TITLE
Quesetion according to target-architecture in release-pipelines

### ISSUE THREAD

**Issue by andife** [onnx/onnx#6260]
# Ask a Question

### Question

In our release pipeline: https://github.com/onnx/onnx/blob/main/.github/workflows/release_mac.yml we have the following:

```
    runs-on: ${{ (matrix.target-architecture == 'x86_64') && 'macos-12' || 'macos-14' }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        target-architecture: ['x86_64', 'arm64']
```
(Introduced at https://github.com/onnx/onnx/commit/453aa2f85ea38198b6d9bc50c9c1942a1f16b6c3)

Why do we hard code "runs-on" and make a strategy for the different architectures?
