### ISSUE TITLE
Version Converter - Upgrading opset requires 6x the disk size of model in memory?

### ISSUE THREAD

**Issue by polarathene** [onnx/onnx#7037]
# Ask a Question

### Question

I have recently found a [1.1GB ONNX model](https://huggingface.co/iiiorg/piiranha-v1-detect-personal-information/blob/refs%2Fpr%2F8/onnx/model.onnx) (_sourced from [this issue](https://github.com/tracel-ai/burn/issues/2968#issuecomment-2763357888)_) to require approx 7GB of memory total to perform an opset upgrade.

- Is there a way to know memory requirements for converting / upgrading ONNX model opsets?
- Could this be optimized to require less memory overhead? (_Perhaps updating/writing chunks to disk during the conversion process if plausible_)

I assume this task would benefit from the ability to prefer lower memory requirements to convert. Presumably a 2GB ONNX model would need approx 12GB+ of RAM.

### Further information

- **Relevant Area:** version_converter

- **Is this issue related to a specific model?:** No

The [Version Converter docs](https://github.com/onnx/onnx/blob/main/docs/VersionConverter.md) note:

> _Implementation wise, the library leverages the **in-memory representation** that is much more convenient to manipulate than the raw protobuf structs, and converters to and from the protobuf format which were developed for the ONNX Optimizer._

This is presumably a contributor for memory usage being much higher (_near 5x the model size to load, and additional 2x for the upgrade itself_).

### Notes

This conversion was performed with a separate python script calling the `version_converter.py` script. It loaded the model with approx 5GB of memory used in the container just for this task (_excludes file buffer I/O memory usage_), and a further 2GB during the upgrade process.

**References:**
- [Version Converter](https://github.com/onnx/onnx/blob/da3b87e4de6162d7b716f5b8e65f77204669d43d/onnx/version_converter.py)
- [Wrapper script used](https://github.com/tracel-ai/burn/blob/1f5ccd43b3f317a5cdb8fef4fcd4ed506d4d190f/crates/burn-import/onnx_opset_upgrade.py) (_a utility script for supporting import of ONNX models into Burn_)
- [`compose.yaml`](https://github.com/tracel-ai/burn/issues/1714#issuecomment-2952373124) was used for producing the reproduction. It has been modified below to focus only on the version converter concern.

In the referenced `compose.yaml`, the model is downloaded along with applying the opset upgrade during the container image build. On a lower spec system this triggered an OOM event that killed my SSH session instead of the build process.

I have found it easier to monitor the container stats in real-time with an active container running. So I have provided a reproduction example `compose.yaml` below to support that.

**NOTE:** I'm not too familiar with Python (_for which there may be better tooling to capture peak memory_), but on Linux there is the option using cgroups and observing `memory.peak`, however that includes the file cache I/O. Since file I/O should be ignored, I've instead preferred to monitor memory use for this task by viewing the container resource stats to observe peak memory usage.

### Reproduction

```yaml
name: example

services:
  burn-onnx-import:
    image: localhost/burn-onnx-import
    # Build custom image (fetches ONNX model + upgrades opset if required),
    # NOTE: Adjust `ONNX_MODEL_URL` ARG for required model
    pull_policy: build
    build:
      args:
        ONNX_MODEL_URL: ${ONNX_MODEL_URL:-https://huggingface.co/iiiorg/piiranha-v1-detect-personal-information/resolve/refs%2Fpr%2F8/onnx/model.onnx}
      # NOTE: To avoid using the Docker Compose ENV interpolation feature, `$` must be escaped as `$$`:
      dockerfile_inline: |
        FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim
        WORKDIR /example

        # Grab the ONNX model and add the ONNX opset upgrade script:
        ARG ONNX_MODEL_URL
        ADD $${ONNX_MODEL_URL?model-url-required} src/model/example.onnx
        # Next release tag after `v0.17.1` could be used to pin, until then only a commit or branch ref works:
        ARG REF=1f5ccd43b3f317a5cdb8fef4fcd4ed506d4d190f
        ARG ONNX_UPGRADE_URL=https://github.com/tracel-ai/burn/raw/$${REF}/crates/burn-import/onnx_opset_upgrade.py
        ADD --chmod=0755 $${ONNX_UPGRADE_URL} onnx-opset-upgrade.py
```

With Docker Compose installed, I run [`oxker`](https://github.com/mrjackwills/oxker) in a separate terminal and start the container, switching to `oxker` to view the running container before I run the `printf` command that begins the conversion:

```bash
# This will build the inlined `Dockerfile` in the above `compose.yaml`,
# then start and shell into the container:
docker compose run --rm -it --name onnx-example burn-onnx-import bash

# Automate the input prompts for the ONNX file read/write paths via printf:
# (NOTE: This may require 6x the file size in memory or more to perform without triggering an OOM)
# (by default containers only allocate to memory and do not use SWAP space)
printf '%s\n' 'src/model/example.onnx' 'src/model/example.onnx' | ./onnx-opset-upgrade.py
```

This results in a memory graph like this for the monitored container in `oxker` (_**6.91 GB** is the peak memory usage recorded while graphing during the conversion process_):

> ![Image](https://github.com/user-attachments/assets/d4439936-f556-4fc0-864a-8228a31da422)

**Comment by justinchuby** [comment]
Feel free to use https://microsoft.github.io/onnxscript/api/generated/onnxscript.version_converter.convert_version.html#onnxscript.version_converter.convert_version , which should be more memory efficient. It does some tricks to offload the weights so that they don’t participate in the version conversion logic.

**Comment by polarathene** [comment]
@justinchuby is that not the call that is made here?:

https://github.com/onnx/onnx/blob/625ab7a2278268fb038b9e37767029bdab93c198/onnx/version_converter.py#L39

I'm not too familiar with ONNX tooling or Python personally, but at a glance the referenced wrapper script is also [calling that same method](https://github.com/tracel-ai/burn/blob/1f5ccd43b3f317a5cdb8fef4fcd4ed506d4d190f/crates/burn-import/onnx_opset_upgrade.py#L53).

I could be mistaken, perhaps something else in that process from the third-party script to upgrade a model to opset 16 is contributing to the memory overhead. If you can confirm that the python call I referenced above is the same one you're advising I'll try reproduce with only that involved.

---

Ok, I came across the source for what you're referring to here:

https://github.com/microsoft/onnxscript/blob/38871a562b21f0475dedc0b2fab1d882aa96c339/onnxscript/version_converter/_version_converter.py#L328

As for usage, am I meant to be calling that directly, or when I clicked the "source" link from the page you referenced, it sent me [here](https://microsoft.github.io/onnxscript/_modules/onnxscript/version_converter.html#convert_version) with some other Python script that has no reference to the GH source, I'm not sure how I should interpret that as the version converter source code I linked at Github is vastly different 😓(_**EDIT:** [Found it](https://github.com/microsoft/onnxscript/blob/38871a562b21f0475dedc0b2fab1d882aa96c339/onnxscript/version_converter/__init__.py), linking the source page to actual source on GH would have been nice_ 😅 )

**Comment by justinchuby** [comment]
Hi-

All you have to do is pip install onnxscript then call

```py
import onnxscript
import onnx_ir as ir 
model = ir.load("model.onnx") # for model <2gb you can use onnx.load as well
onnxscript.version_converter.convert_version(model, your_new_version)
ir.save(model, "converted_model.onnx") # for model < 2gb you can use onnx.save as well
```


It will be calling the same version converter code you linked above, but differently: the memory usage you are seeing happens when the logic takes the model from Python to c++, which requires serialization every time it crosses the api boundary. The method in onnxscript temporarily removes the weights from the model. So the part that needs to be serialized become very small. 

> The link

Thanks for the suggestion. The documentation was generated. There’s some plugin we can use to link to github. I will look into it soon

**Comment by polarathene** [comment]
> So the part that needs to be serialized become very small.

It seems to be a little better? (1GB less) Still quite high though, am I doing something wrong? 🤔 

`oxker` monitoring of memory usage for the container:

> ![Image](https://github.com/user-attachments/assets/d347ccea-8f80-4d4c-8d1e-5b3e20b79783)

`btop` process monitor on the host (_rough screenshot timing so appears bit lower, another run it was 5.7 GiB_):

> ![Image](https://github.com/user-attachments/assets/631fecc0-3095-4adc-b12a-404899bd4f58)

---

## Reproduction

**`compose.yaml`:**

```yaml
name: example

services:
  burn-onnx-import:
    image: localhost/burn-onnx-import
    pull_policy: build
    configs:
      - source: onxx-upgrade-script
        target: /example/onnx-upgrade-opset.py
        mode: 0755
    build:
      dockerfile_inline: |
        FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim
        WORKDIR /example

        # Grab the ONNX model:
        ADD \
          https://huggingface.co/iiiorg/piiranha-v1-detect-personal-information/resolve/refs%2Fpr%2F8/onnx/model.onnx \
          src/model/example.onnx

configs:
  onxx-upgrade-script:
    content: |
      #!/usr/bin/env -S uv run --script

      # /// script
      # dependencies = [
      #   "onnxscript==0.3.0",
      # ]
      # ///

      import onnxscript
      import onnx_ir as ir

      model = ir.load("src/model/example.onnx") # for model <2gb you can use onnx.load as well
      onnxscript.version_converter.convert_version(model, 18)
      ir.save(model, "src/model/example.onnx") # for model < 2gb you can use onnx.save as well
```

```bash
docker compose run --rm -it burn-import-onnx ./onnx-upgrade-opset.py
```

---

While the script above works, I was curious if the advice to use the `onnx` instead of `ir` load/save methods might improve the memory usage (_the model is only 1.1GB in size_). I made sure to also add `import onnx` to use these two methods.

That failed with:

```python
Traceback (most recent call last):
  File "/example/./onnx-upgrade-opset.py", line 16, in <module>
    onnxscript.version_converter.convert_version(model, 18)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/root/.cache/uv/environments-v2/onnx-upgrade-opset-cb5f306740f92124/lib/python3.13/site-packages/onnxscript/version_converter/__init__.py", line 173, in convert_version
    del model_proto.functions
        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: Cannot delete field attribute
```
